# Generated by Django 4.2.5 on 2023-10-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notes_options_homework'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'homework', 'verbose_name_plural': 'homework'},
        ),
    ]
